..F...................FFF....F..F..FFFF...........
======================================================================
FAIL: TestRst_10_LiteralBlock3; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 210, in __test_writer
    diff )
AssertionError: pxml tree mismatch 
 on </srv/project-mpe/docutils-ext/var/test-rst.10.literal-block-3.rst>

---  

+++  

@@ -5,8 +5,11 @@

         or quoted text is a literal block.
     <literal_block xml:space="preserve">
         Whitespace, newlines, blank lines, and
-        all kinds of markup (like *this* or
-        \this) is preserved by literal blocks.
+        all kinds of markup (like 
+        <emphasis>
+            this
+         or
+        this) is preserved by literal blocks.
         
         The paragraph containing only '::'
         will be omitted from the result.

======================================================================
FAIL: TestRst_1_Document5_FullRstDemo; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 137, in _test_writer
    self.fail(e)
AssertionError: /srv/project-mpe/docutils-ext/var/test-rst.1.document-5.full-rst-demo.rst:67: (SEVERE/4) Title level inconsistent:

2.1.1\xa0\xa0\xa0Inline Markup
^^^^^^^^^^^^^

======================================================================
FAIL: TestRst_1_Document6; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 203, in __test_writer
    warnings)
AssertionError: Error re-parsing generated file
 on </srv/project-mpe/docutils-ext/var/test-rst.1.document-6.rst>

/srv/project-mpe/docutils-ext/var/test-rst.1.document-6.rst:8: (WARNING/2) Bibliographic field "Authors" incompatible with extraction: it must contain either a single paragraph (with authors separated by one of ";,"), multiple paragraphs (one per author), or a bullet list with one paragraph (one author) per item.
/srv/project-mpe/docutils-ext/var/test-rst.1.document-6.rst:: (ERROR/3) Unknown target name: "goodger@python.org".


======================================================================
FAIL: TestRst_1_Document7; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 210, in __test_writer
    diff )
AssertionError: pxml tree mismatch 
 on </srv/project-mpe/docutils-ext/var/test-rst.1.document-7.rst>

---  

+++  

@@ -11,16 +11,12 @@

                 The fanatics going straight forward and openly, the politicians by the surer mode of zigzag.
         <attribution>
             Burke.
-    <enumerated_list enumtype="arabic" prefix="" start="2" suffix=".">
-        <list_item>
-            <paragraph>
-                (Arch.) A molding running in a zigzag line; a chevron, or series of chevrons.
-        <list_item>
-            <paragraph>
-                (Fort.) See Boyau. 
-                <footnote_reference auto="1" ids="id1" refid="id2">
-                    1
-    <footnote auto="1" backrefs="id1" ids="id2" names="1">
+    <paragraph>
+        2. (Arch.) A molding running in a zigzag line; a chevron, or series of chevrons.
+        2. (Fort.) See Boyau. 
+        <footnote_reference ids="id1" refid="id2">
+            1
+    <footnote auto="1" ids="id2" names="1">
         <label>
             1
         <paragraph>

======================================================================
FAIL: TestRst_22_Docinfo; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 203, in __test_writer
    warnings)
AssertionError: Error re-parsing generated file
 on </srv/project-mpe/docutils-ext/var/test-rst.22.docinfo.rst>

/srv/project-mpe/docutils-ext/var/test-rst.22.docinfo.rst:8: (WARNING/2) Bibliographic field "Authors" incompatible with extraction: it must contain either a single paragraph (with authors separated by one of ";,"), multiple paragraphs (one per author), or a bullet list with one paragraph (one author) per item.
/srv/project-mpe/docutils-ext/var/test-rst.22.docinfo.rst:: (ERROR/3) Unknown target name: "goodger@python.org".


======================================================================
FAIL: TestRst_2_Title1; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 137, in _test_writer
    self.fail(e)
AssertionError: /srv/project-mpe/docutils-ext/var/test-rst.2.title-1.rst:10: (SEVERE/4) Title level inconsistent:

Title
^^^^^

======================================================================
FAIL: TestRst_5_Inline1; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 203, in __test_writer
    warnings)
AssertionError: Error re-parsing generated file
 on </srv/project-mpe/docutils-ext/var/test-rst.5.inline-1.rst>

/srv/project-mpe/docutils-ext/var/test-rst.5.inline-1.rst:9: (ERROR/3) Indirect hyperlink target "reference" (id="reference") refers to target "target", which does not exist.


======================================================================
FAIL: TestRst_5_Inline2; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 203, in __test_writer
    warnings)
AssertionError: Error re-parsing generated file
 on </srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst>

/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:5: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:7: (WARNING/2) malformed hyperlink target.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:25: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:30: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:31: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:33: (WARNING/2) Definition list ends without a blank line; unexpected unindent.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:33: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:35: (WARNING/2) malformed hyperlink target.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:37: (WARNING/2) malformed hyperlink target.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:: (ERROR/3) Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-2.rst:5: (ERROR/3) Unknown target name: "anonymous inline reference".


======================================================================
FAIL: TestRst_5_Inline3; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 203, in __test_writer
    warnings)
AssertionError: Error re-parsing generated file
 on </srv/project-mpe/docutils-ext/var/test-rst.5.inline-3.rst>

/srv/project-mpe/docutils-ext/var/test-rst.5.inline-3.rst:10: (ERROR/3) Unknown interpreted text role "role".
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-3.rst:12: (ERROR/3) Unknown interpreted text role "role".
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-3.rst:14: (ERROR/3) Unknown interpreted text role "role".


======================================================================
FAIL: TestRst_5_Inline4; Lossy doctree comparison; Writer 'rst-mpe'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/docutils-ext/test/util.py", line 228, in runTest
    self._test_writer(writer_class(), lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 135, in _test_writer
    self.__test_writer(writer, lossy=lossy)
  File "/srv/project-mpe/docutils-ext/test/util.py", line 203, in __test_writer
    warnings)
AssertionError: Error re-parsing generated file
 on </srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst>

/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:13: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:38: (ERROR/3) Content block expected for the "replace" directive; none found.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:38: (WARNING/2) Substitution definition "EXAMPLE" empty or invalid.

.. |EXAMPLE| replace::

/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:3: (ERROR/3) Too many symbol footnote references: only 0 corresponding footnotes available.
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:3: (ERROR/3) Unknown target name: "example".
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:3: (ERROR/3) Unknown target name: "python web site".
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:3: (ERROR/3) Unknown target name: "cit2002".
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:17: (ERROR/3) Unknown target name: "pep 287".
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:17: (ERROR/3) Unknown target name: "rfc 2822".
/srv/project-mpe/docutils-ext/var/test-rst.5.inline-4.rst:49: (ERROR/3) Unknown target name: "label".


----------------------------------------------------------------------
Ran 50 tests in 3.361s

FAILED (failures=10)
